fixtures:
  symlinks:
    kairosdb: "#{source_dir}"
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      tag:  '4.6.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      tag:  '1.2.2'
    staging:
      repo: 'https://github.com/nanliu/puppet-staging.git'
      tag:  '1.0.3'
